# Generated by Django 5.0.3 on 2026-04-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('ecosystem', models.CharField(choices=[('npm', 'npm'), ('pypi', 'PyPI'), ('maven', 'Maven'), ('rubygems', 'RubyGems')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_malicious', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='safe', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('behavior_analysis', models.JSONField(default=dict)),
                ('alternative_suggestions', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.package')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
